# Generated by Django 3.2.5 on 2021-07-29 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='header_title',
            old_name='blog_name',
            new_name='name',
        ),
    ]
