# Generated by Django 3.2.5 on 2021-07-29 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_blog_name_header_title_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Header_title',
            new_name='Header',
        ),
    ]
